### ISSUE TITLE
Dates on X axis ?

### ISSUE THREAD

**Issue by c0ze** [cgsimmons/covid-graph#2]
Hey, nice project !
I have a question, is it possible to get dates on the X axis ?

**Comment by cgsimmons** [comment]
There really isn't room to get date info within a single character, but I could add tick marks and include the date range as part of the result text at the bottom. Like "(12/5/2020 - 12/25/2020)".

**Comment by cgsimmons** [comment]
Added the text and a fancy box
https://github.com/cgsimmons/covid-graph/pull/4
